import { Plan, User, type PlanType } from "@/types";

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Carlos M.",
    age: 26,
    gender: "male",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos",
    bio: "Amante de la música electrónica y el buen ambiente",
    interests: ["EDM", "Rooftops", "Cocteles"],
    verified: true,
    rating: 4.8,
    eventsHosted: 12,
    eventsAttended: 34,
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    name: "María G.",
    age: 24,
    gender: "female",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Maria",
    bio: "Siempre lista para una buena fiesta",
    interests: ["Reggaeton", "Karaoke", "Dancing"],
    verified: true,
    rating: 4.9,
    eventsHosted: 8,
    eventsAttended: 45,
    createdAt: new Date("2024-02-20"),
  },
  {
    id: "3",
    name: "Ana R.",
    age: 28,
    gender: "female",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ana",
    bio: "Explorando la vida nocturna de la ciudad",
    interests: ["Jazz", "Wine bars", "Networking"],
    verified: true,
    rating: 4.7,
    eventsHosted: 5,
    eventsAttended: 22,
    createdAt: new Date("2024-03-10"),
  },
  {
    id: "4",
    name: "Diego L.",
    age: 25,
    gender: "male",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Diego",
    bio: "DJ aficionado, siempre buscando nuevos spots",
    interests: ["House", "Techno", "After parties"],
    verified: false,
    rating: 4.5,
    eventsHosted: 3,
    eventsAttended: 18,
    createdAt: new Date("2024-04-05"),
  },
];

const now = new Date();
const tonight = new Date(now);
tonight.setHours(22, 0, 0, 0);

const inTwoHours = new Date(now.getTime() + 2 * 60 * 60 * 1000);
const inThreeHours = new Date(now.getTime() + 3 * 60 * 60 * 1000);

export const mockPlans: Plan[] = [
  {
    id: "1",
    title: "¿Quién para ir al Six?",
    description:
      "Busco grupo para ir al antro Six esta noche. Tengo mesa reservada para 8 personas, faltan 4. Ambiente chill, buen reggaeton y electrónica.",
    type: "club" as PlanType,
    location: {
      name: "Club Six",
      address: "Av. Insurgentes Sur 1234, CDMX",
      coordinates: { lat: 19.4326, lng: -99.1332 },
    },
    dateTime: tonight,
    host: mockUsers[0],
    participants: [mockUsers[1]],
    maxParticipants: 8,
    minParticipants: 4,
    budget: 3,
    ageRange: { min: 22, max: 32 },
    genderPreference: "all",
    tags: ["reggaeton", "electrónica", "mesa VIP"],
    imageUrl: "https://images.unsplash.com/photo-1566737236500-c8ac43014a67?w=800",
    status: "open",
    createdAt: new Date(),
  },
  {
    id: "2",
    title: "Karaoke Night en Voicebox",
    description:
      "Noche de karaoke con room privado. Todos los géneros bienvenidos, lo importante es pasarla bien y cantar (aunque sea mal jaja)",
    type: "karaoke" as PlanType,
    location: {
      name: "Voicebox Karaoke",
      address: "Calle Roma 567, Roma Norte",
      coordinates: { lat: 19.4195, lng: -99.1617 },
    },
    dateTime: inTwoHours,
    host: mockUsers[1],
    participants: [mockUsers[2]],
    maxParticipants: 10,
    minParticipants: 4,
    budget: 2,
    ageRange: { min: 21, max: 35 },
    genderPreference: "all",
    tags: ["karaoke", "música", "diversión"],
    imageUrl: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800",
    status: "open",
    createdAt: new Date(),
  },
  {
    id: "3",
    title: "Rooftop chill + sunset",
    description:
      "Atardecer en rooftop con vista increíble de la ciudad. Ambiente relajado, buenos drinks y buena plática. Perfecto para conocer gente nueva.",
    type: "rooftop" as PlanType,
    location: {
      name: "Supra Rooftop",
      address: "Av. Presidente Masaryk 201, Polanco",
      coordinates: { lat: 19.4329, lng: -99.1893 },
    },
    dateTime: inThreeHours,
    host: mockUsers[2],
    participants: [],
    maxParticipants: 6,
    minParticipants: 3,
    budget: 4,
    ageRange: { min: 25, max: 40 },
    genderPreference: "all",
    tags: ["rooftop", "chill", "networking", "sunset"],
    imageUrl: "https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800",
    status: "open",
    createdAt: new Date(),
  },
  {
    id: "4",
    title: "Pre-party en mi depa",
    description:
      "Antes de salir al antro, pre en mi departamento. Trae tu propia bebida, yo pongo las botanas y el sistema de sonido.",
    type: "house-party" as PlanType,
    location: {
      name: "Departamento en Condesa",
      address: "Colonia Condesa, CDMX",
      coordinates: { lat: 19.4117, lng: -99.1724 },
    },
    dateTime: tonight,
    host: mockUsers[3],
    participants: [mockUsers[0], mockUsers[1]],
    maxParticipants: 12,
    minParticipants: 5,
    budget: 1,
    ageRange: { min: 21, max: 30 },
    genderPreference: "all",
    tags: ["prepartry", "casa", "byob", "dj set"],
    imageUrl: "https://images.unsplash.com/photo-1429514513361-8fa32282fd5f?w=800",
    status: "open",
    createdAt: new Date(),
  },
];
